name: Release
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      RUNNER: github
      NODE_ENV: test
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
      - name: Create directories
        run: cp .env.example .env.test
      - name: Setup .env file
        run: |
          echo FACEBOOK_CONSUMER_ID = "${{ secrets.FACEBOOK_CONSUMER_ID }}" >> .env.test
          echo FACEBOOK_CONSUMER_SECRET = "${{ secrets.FACEBOOK_CONSUMER_SECRET }}" >> .env.test
          echo GITHUB_CONSUMER_ID = "${{ secrets.GTHB_CONSUMER_ID }}" >> .env.test
          echo GITHUB_CONSUMER_SECRET = "${{ secrets.GTHB_CONSUMER_SECRET }}" >> .env.test
          echo GOOGLE_CONSUMER_ID = "${{ secrets.GOOGLE_CONSUMER_ID }}" >> .env.test
          echo GOOGLE_CONSUMER_SECRET = "${{ secrets.GOOGLE_CONSUMER_SECRET }}" >> .env.test
          echo LINKEDIN_CONSUMER_ID = "${{ secrets.LINKEDIN_CONSUMER_ID }}" >> .env.test
          echo LINKEDIN_CONSUMER_SECRET = "${{ secrets.LINKEDIN_CONSUMER_SECRET }}" >> .env.test
      - name: Install global dependencies
        run:  npm i typescript@5.7.2 -g
      - name: Install local dependencies
        run: npm i
      - name: Compile Typescript files
        run: tsc
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            dist
          retention-days: 3
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      RUNNER: github
      NODE_ENV: test
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
      - name: Setup MySQL server
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7' 
          mysql database: 'typeplate_test'
          mysql root password: passw0rd
      - name: Install global dependencies
        run:  npm i typescript@5.7.2 -g
      - name: Install local dependencies
        run:  npm i
      - name: Create dist directory
        run: mkdir dist
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist
      - name: Synchronize database schema
        run: npm run schema:sync
      - name: Execute tests suites
        run: npm run ci:test
      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./reports/coverage/lcov.info
  release:
    name: Release on Github
    runs-on: ubuntu-latest
    needs: [ build, test ]
    steps:
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashfiles('**/package-lock.json') }}
      - name: Github checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
      - name: Create release
        uses: konfer-be/action-create-release-from-tag@v1.0.12
        with:
          token: ${{ secrets.GITHUB_TOKEN }}